name: Update Static JS Files

on:
  push:
    paths:
        - 'js/**'
    branches:
        - master

jobs:
  update-static-js-files:
    runs-on: ubuntu-latest
    name: "Update Static JS-Files"
    steps:
      - uses: actions/checkout@v3
        # > if the push needs to trigger other workflows, use a repo scoped Personal Acces Token
        # see: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457
        # with:
        #   token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -f py/visdom/static/js/main.js py/visdom/static/js/main.js.map
          git commit -m "update static/js files"
          git push

